---
# netdata-server/tasks/main.yml

- name: 'Populate the package name variable depending on the OS'
  ansible.builtin.include: package_name.yml

- name: 'Add the netdata repository'
  ansible.builtin.include: repository.yml

- name: 'Flush handlers to trigger refresh of repository'
  ansible.builtin.meta: flush_handlers

- name: 'Install the packages'
  ansible.builtin.package:
    name: "{{ netdata_server_packages }}"
    state: 'present'

- name: 'Include tasks to create stream.conf if desired'
  ansible.builtin.include: receive_streams.yml
  when:
    - 'receive_streams | bool'

- name: 'Start the service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'started'

- name: 'Enable the service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    enabled: 'true'
