---
# netdata-server/tasks/receive_streams.yml

- name: 'Create the streams.conf'
  ansible.builtin.template:
    src: 'stream.conf.j2'
    dest: '/etc/netdata/stream.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the netdata service'

- name: 'Add web section to netdata.conf'
  ansible.builtin.blockinfile:
    path: '/etc/netdata/netdata.conf'
    block: |
      [web]
          mode = static-threaded
          accept a streaming request every seconds = 0
  notify:
    - 'Restart the netdata service'
