---
# netdata-server/handlers/main.yml

- name: 'Run zypper refresh on openSUSE/SUSE'
  community.general.zypper_repository:
    name: '*'
    runrefresh: 'true'
  when:
    - 'ansible_os_family == "Suse"'

- name: 'Restart the netdata service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'
