---
# netdata-server/handlers/main.yml

- name: 'openSUSE/SUSE: zypper refresh'
  zypper_repository:
    name: '*'
    runrefresh: 'true'
  when:
    - 'ansible_os_family == "Suse"'

- name: 'Restart the netdata service'
  service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'
